config/routes.rb
Rails.application.routes.draw do
  root to: 'schedules#index'  
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :user
    
    validates :content, presence: true, length: { maximum: 255 }
    validates :end_time, presence: true
    validates :start_time, presence: true, numericality: { less_than: :end_time}
    
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
     end
  end

  
  def counts(user)
    @count_schedules = user.schedules.count
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @pagy, @schedules = pagy(current_user.schedules.order(id: :desc), items: 5)
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = current_user.schedules.build(schedule_params)

    if @schedule.save
      flash[:success] = '予定が作成されました。'
      redirect_to root_url
    else
      flash.now[:danger] = '情報に不足があります。'
      render :new
    end
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      flash[:success] = '予定が更新されました'
      redirect_to root_url
    else
      flash.now[:danger] = '予定が更新されませんでした'
      render :edit
    end
  end

  def destroy
    @schedule.destroy

    flash[:success] = '予定は削除されました'
    redirect_to root_url
  end
  
  private
  
  def schedule_params
    params.require(:schedule).permit(:content, :start_time, :end_time, :user)
  end
  
  def correct_user
    @schedule = current_user.schedules.find_by(id: params[:id])
    unless @schedule
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">MySchedule</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Schedules</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script> 
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: @schedule) do |f| %>
      <% if schedule.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul>
            <% schedule.errors.full_messages.each do |error_msg| %>
              <li><%= error_msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="mb-3">
      　<%= f.label :content, 'タスク: ' %>
      　<%= f.text_field :content, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label :start_time, '開始時間: ' %>
        <%= f.datetime_select :start_time, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label :end_time, '終了時間: ' %>
        <%= f.datetime_select :end_time, class: 'form-control' %>
      </div>
      
      <%= f.submit 'OK' %>
    <% end %>
  </div>
</div>

app/views/schedules/edit.html.erb
<h1>Schedule <%= @schedule.id %> の編集ページ</h1>

<%= render 'form', schedule: @schedule %>

app/views/schedules/index.html.erb
<% if logged_in? %>
  <h1>タスク一覧</h1>
  <% if @schedules.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>id</th>
          <th>内容</th>
          <th>開始時間</th>
          <th>終了時間</th>
        </tr>
      </thead>
      <tbody>
        <% @schedules.each do |schedule| %>
          <tr>
            <td><%= link_to schedule.id, schedule %></td>
            <td><%= schedule.content %></td>
            <td><%= schedule.start_time.strftime("%Y/%m/%d %H:%M") %></td>
            <td><%= schedule.end_time.strftime("%Y/%m/%d %H:%M") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  <% end %>
  <%= link_to '新規タスク投稿', new_schedule_path, class: "btn btn-primary" %>
  
<% else %>
  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>Welcome to MySchedule</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/schedules/new.html.erb
<h1>新規作成ページ</h1>

<%= render 'form', schedule: @schedule %>

app/views/schedules/show.html.erb
<h1>Schedule <%= @schedule.id %> の詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @schedule.id %></td>
  </tr>
  <tr>
    <th>タスク</th>
    <td><%= @schedule.content %></td>
  </tr>
  <tr>
    <th>開始時間</th>
    <td><%= @schedule.start_time.strftime("%Y/%m/%d %H:%M") %></td>
  </tr>
  <tr>
    <th>終了時間</th>
    <td><%= @schedule.end_time.strftime("%Y/%m/%d %H:%M") %></td>
  </tr>
</table>

<%= link_to 'このタスクを編集する', edit_schedule_path(@schedule), class: 'btn btn-light' %>
<%= link_to 'このタスクを削除する', @schedule, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

<%= link_to '一覧に戻る', schedules_path, class: 'btn btn-primary'%>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>